---
abstract: 'Encrypted, expiring, compressed, serialized session data with integrity'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::Deep: 0
  Test::Fatal: 0
  Test::More: 0.96
  Test::Tolerant: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Session-Storage-Secure
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Session::Storage::Secure:
    file: lib/Session/Storage/Secure.pm
    version: 0.005
requires:
  Carp: 0
  Crypt::CBC: 0
  Crypt::Rijndael: 0
  Crypt::URandom: 0
  Digest::SHA: 0
  MIME::Base64: 3.12
  Math::Random::ISAAC::XS: 0
  Moo: 0
  MooX::Types::MooseLike::Base: 0
  Sereal::Decoder: 0
  Sereal::Encoder: 0
  namespace::clean: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/session-storage-secure/issues
  homepage: https://metacpan.org/release/Session-Storage-Secure
  repository: git://github.com/dagolden/session-storage-secure.git
version: 0.005
