use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006000
eval "use Test::Spelling 0.12; use Pod::Wordlist::hanekomu; 1" or die $@;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
AES
Don'ts
Fu
HMAC
Liu
MAC's
Rekeying
Sereal
al
authenticator
ciphertext
cryptographically
decrypting
et
login
scalability
unencrypted
David
Golden
dagolden
lib
Session
Storage
Secure
